[package]
name = "test_util"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
# In alphabetical order
arrow = { workspace = true }
chrono = { workspace = true }
common_types = { workspace = true, features = ["test"] }
env_logger = { workspace = true }
