[package]
name = "ceresdb"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
edition = "2021"

[workspace]
# In alphabetical order
members = [
    "analytic_engine",
    "arrow_deps",
    "benchmarks",
    "catalog",
    "catalog_impls",
    "cluster",
    "common_types",
    "common_util",
    "components/arena",
    "components/bytes",
    "components/logger",
    "components/object_store",
    "components/parquet",
    "components/profile",
    "components/skiplist",
    "components/table_kv",
    "components/tracing_util",
    "df_operator",
    "interpreters",
    "meta_client",
    "proto",
    "query_engine",
    "server",
    "sql",
    "system_catalog",
    "table_engine",
    "tests/harness",
    "wal",
]

[[bin]]
name = "ceresdb-server"
path = "src/bin/ceresdb-server.rs"

[workspace.dependencies]
tonic = "0.8.1"

[dependencies]
analytic_engine = { path = "analytic_engine" }
async-trait = "0.1.53"
catalog = { path = "catalog" }
catalog_impls = { path = "catalog_impls" }
clap = "2.0"
cluster = { path = "cluster" }
common_util = { path = "common_util" }
df_operator = { path = "df_operator" }
log = "0.4"
logger = { path = "components/logger" }
meta_client = { path = "meta_client" }
query_engine = { path = "query_engine" }
server = { path = "server" }
table_engine = { path = "table_engine" }
tracing_util = { path = "components/tracing_util" }

# Crates.io dependencies, in alphabetical order
signal-hook = "0.3"

[build-dependencies]
vergen = { version = "5", default-features = false, features = ["build", "git"] }

[profile.release]
debug = true
opt-level = 2
overflow-checks = true

[profile.bench]
debug = true
