[package]
name = "ceresdb"
version = "1.0.0-alpha02"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

[workspace.package]
version = "1.0.0-alpha02"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

[workspace]
# In alphabetical order
members = [
    "analytic_engine",
    "benchmarks",
    "catalog",
    "catalog_impls",
    "cluster",
    "common_types",
    "common_util",
    "components/arena",
    "components/arrow_ext",
    "components/bytes_ext",
    "components/logger",
    "components/message_queue",
    "components/object_store",
    "components/parquet_ext",
    "components/profile",
    "components/skiplist",
    "components/table_kv",
    "components/tracing_util",
    "df_operator",
    "integration_tests",
    "interpreters",
    "meta_client",
    "proto",
    "query_engine",
    "remote_engine_client",
    "router",
    "server",
    "sql",
    "system_catalog",
    "table_engine",
    "tools",
    "wal",
]

[[bin]]
name = "ceresdb-server"
path = "src/bin/ceresdb-server.rs"

[workspace.dependencies]
arrow = { version = "23.0.0", features = ["prettyprint"] }
arrow_ipc = { version = "23.0.0" }
arrow_ext = { path = "components/arrow_ext" }
analytic_engine = { path = "analytic_engine" }
arena = { path = "components/arena" }
async-trait = "0.1.53"
base64 = "0.13"
bytes = "1.1.0"
bytes_ext = { path = "components/bytes_ext" }
catalog = { path = "catalog" }
catalog_impls = { path = "catalog_impls" }
chrono = "0.4"
clap = "3.0"
clru = "0.6.1"
cluster = { path = "cluster" }
criterion = "0.3"
common_types = { path = "common_types" }
common_util = { path = "common_util" }
df_operator = { path = "df_operator" }
env_logger = "0.6"
ethbloom = "0.13.0"
futures = "0.3"
lazy_static = "1.4.0"
log = "0.4"
logger = { path = "components/logger" }
lru = "0.7.6"
interpreters = { path = "interpreters" }
meta_client = { path = "meta_client" }
object_store = { path = "components/object_store" }
parquet_ext = { path = "components/parquet_ext" }
parquet = { version = "23.0.0" }
paste = "1.0"
profile = { path = "components/profile" }
prometheus = "0.12"
prometheus-static-metric = "0.5"
proto = { path = "proto" }
prost = "0.11"
query_engine = { path = "query_engine" }
rand = "0.7"
remote_engine_client = { path = "remote_engine_client" }
router = { path = "router" }
snafu = { version = "0.6.10", features = ["backtraces"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.60"
server = { path = "server" }
smallvec = "1.6"
slog = "2.7"
sql = { path = "sql" }
system_catalog = { path = "system_catalog" }
table_engine = { path = "table_engine" }
table_kv = { path = "components/table_kv" }
tempfile = "3.1.0"
tracing_util = { path = "components/tracing_util" }
tonic = "0.8.1"
tokio = { version = "1.25", features = ["full"] }
wal = { path = "wal" }
message_queue = { path = "components/message_queue" }
zstd = { version = "0.12", default-features = false }

[workspace.dependencies.ceresdbproto]
git = "https://github.com/CeresDB/ceresdbproto.git"
rev = "55495dd395d12a1f97f6c98e355290671d107c44"

[workspace.dependencies.datafusion]
git = "https://github.com/CeresDB/arrow-datafusion.git"
rev = "d84ea9c79c9e83ff0b4dadf8880a4983af59ef48"

[workspace.dependencies.datafusion-expr]
git = "https://github.com/CeresDB/arrow-datafusion.git"
rev = "d84ea9c79c9e83ff0b4dadf8880a4983af59ef48"

[workspace.dependencies.datafusion-proto]
git = "https://github.com/CeresDB/arrow-datafusion.git"
rev = "d84ea9c79c9e83ff0b4dadf8880a4983af59ef48"

[dependencies]
analytic_engine = { workspace = true }
catalog = { workspace = true }
catalog_impls = { workspace = true }
clap = { workspace = true }
cluster = { workspace = true }
common_util = { workspace = true }
df_operator = { workspace = true }
interpreters = { workspace = true }
log = { workspace = true }
logger = { workspace = true }
meta_client = { workspace = true }
query_engine = { workspace = true }
router = { workspace = true }
server = { workspace = true }
signal-hook = "0.3"
sort = "0.8.5"
table_engine = { workspace = true }
tracing_util = { workspace = true }

[build-dependencies]
vergen = { version = "5", default-features = false, features = ["build", "git"] }

# This profile optimizes for good runtime performance.
[profile.release]
# reference: https://doc.rust-lang.org/rustc/codegen-options/index.html#codegen-units
codegen-units = 1
debug = true
overflow-checks = true

# This profile is used to produce a smaller (no symbols) binary with a little bit poorer performance,
# but with a faster speed and low memory consumption required by compiling.
[profile.release-slim]
inherits = "release"
codegen-units = 16
debug = false
strip = true
