# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

headerPath = "Apache-2.0-ASF.txt"

excludes = [
    # Derived
    "horaemeta/server/coordinator/scheduler/nodepicker/hash/consistent_uniform_test.go",
    "horaemeta/server/coordinator/scheduler/nodepicker/hash/consistent_uniform.go",
    "horaemeta/server/service/http/route.go",
    "src/server/src/federated.rs",
    "src/server/src/session.rs",
    "src/components/skiplist/benches/bench.rs",
    "src/components/skiplist/src/lib.rs",
    "src/components/skiplist/src/key.rs",
    "src/components/skiplist/src/list.rs",
    "src/components/skiplist/tests/tests.rs",
    "src/components/skiplist/Cargo.toml",
    "src/components/size_ext/src/lib.rs",
    "src/components/future_ext/src/cancel.rs",
    "src/components/tracing_util/src/lib.rs",
    "src/components/tracing_util/src/logging.rs",
    "src/components/tracing_util/Cargo.toml",
    "DISCLAIMER",
    "NOTICE",
    "horaemeta/DEPENDENCIES.csv",
    "DEPENDENCIES.tsv",
    # Test files
    "*snap",
    "*result"
]
