[package]
name = "skiplist"
authors = ["Jay Lee <busyjaylee@gmail.com>", "HoraeDB Authors"]

[package.license]
workspace = true

[package.version]
workspace = true

[package.edition]
workspace = true

[dependencies]
arena = { workspace = true }
bytes = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
yatp = { git = "https://github.com/tikv/yatp.git", rev = "793be4d789d4bd15292fe4d06e38063b4ec9d48e" }

[[bench]]
name = "bench"
harness = false
