[package]
name = "arena"
version = "0.1.0"
authors = ["Ruihang Xia <xrh262829@antgroup.com>"]

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.11.1"