[package]
name = "trace_metric_derive_tests"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
trace_metric = { workspace = true }
