[package]
name = "interpreters"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# In alphabetical order
async-trait = { workspace = true }
catalog = { workspace = true }
common_types = { workspace = true }
common_util = { workspace = true }
datafusion = { workspace = true }
datafusion-expr = { workspace = true }
df_operator = { workspace = true }
log = { workspace = true }
meta_client = { workspace = true }
snafu = { workspace = true }
sql = { workspace = true }
table_engine = { workspace = true }
query_engine = { workspace = true }
arrow = { workspace = true }

[dev-dependencies]
analytic_engine = { workspace = true, features = ["test"] }
catalog_impls = { workspace = true }
sql = { workspace = true, features = ["test"] }
tokio = { workspace = true }
