[package]
name = "interpreters"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# In alphabetical order
async-trait = "0.1.53"
catalog = { path = "../catalog" }
common_types = { path = "../common_types" }
common_util = { path = "../common_util" }
df_operator = { path = "../df_operator" }
log = "0.4"
snafu = { version ="0.6.10", features = ["backtraces"]}
sql = { path = "../sql" }
table_engine = { path = "../table_engine" }
query_engine = { path = "../query_engine" }
arrow_deps = { path = "../arrow_deps" }

[dev-dependencies]
analytic_engine = { path = "../analytic_engine", features = ["test"] }
catalog_impls = { path = "../catalog_impls" }
sql = { path = "../sql", features = ["test"] }
tokio = { version = "1.0", features = ["sync", "time"] }
