[package]
name = "profile"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
log = { workspace = true }
tempfile = { workspace = true }
heappy = { git = "https://github.com/mkmik/heappy", rev = "99a7ae15a49de3fdb4cc82abc0ead01df7a0db7d", features = ["enable_heap_profiler", "measure_free"], optional = true }
