name: Bug Report
labels: ["bug"]
description: Report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe this problem
      description: What this problem is and what happened.
    validations:
      required: true
  - type: textarea
    id: server-version
    attributes:
      label: Server version
      description: Which CeresDB server version are you using when this issue arises.
      placeholder: You can get version with `ceresdb-server --version` and paste the output here.
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: Steps to reproduce
      description: How to reproduce this problem.
      placeholder: Paste the command you've typed and logs you get here.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: What is your expected behavior.
  - type: textarea
    id: context
    attributes:
      label: Additional Information
      description: If possible, please attach other context you think may relate to this problem. Like *runtime environment*, *modified config*, *error log* etc.
