name: Question
labels: ["question"]
description: Ask question about CeresDB
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this!
  - type: textarea
    id: area
    attributes:
      label: Which part is this question about
      description: Define the area of this question.
      placeholder: Is it code base, usage, deployment, documentation or some other part?
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Describe your question
      description: A clear and concise description of what the question is.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.