[package]
name = "common_util"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test = ["env_logger"]

[dependencies]
# In alphabetical order
arrow_deps = { path = "../arrow_deps" }
backtrace = "0.3.9"
common_types = { path = "../common_types", features = ["test"] }
chrono = "0.4"
crossbeam-utils = "0.8.7"
env_logger = { version = "0.6", optional = true }
lazy_static = { workspace = true }
libc = "0.2"
log = { workspace = true }
logger = { path = "../components/logger"}
snafu = { workspace = true }
serde = {version = "1.0.81", features = ["derive"]}
serde_derive = "1.0.81"
pin-project-lite = "0.2.8"
prometheus = { workspace = true }
proto = { workspace = true }
time = "0.1"
tokio = { version = "1.15", features = ["full"] }
toml = "0.5"

[dev-dependencies]
env_logger = { workspace = true }
gag = "1.0"
nix = "0.22"
slog = "2.7"
tempfile = "3.1.0"
tokio-test = "0.4.2"

[dev-dependencies.slog-global]
version = "0.1"
git = "https://github.com/tikv/slog-global.git"
rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9"
