[package]
name = "object_store"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
ceresdbproto = { workspace = true }
chrono = { workspace = true }
clru = { workspace = true }
crc = "3.0.0"
futures = { workspace = true }
generic_error = { workspace = true }
hash_ext = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
macros = { workspace = true }
partitioned_lock = { workspace = true }
prometheus = { workspace = true }
prometheus-static-metric = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
runtime = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
size_ext = { workspace = true }
snafu = { workspace = true }
table_kv = { workspace = true }
time_ext = { workspace = true }
tokio = { workspace = true }
twox-hash = "1.6"
upstream = { package = "object_store", version = "0.5.6", features = [ "aws" ] }
uuid = { version = "1.3.3", features = ["v4"] }

[dev-dependencies]
tempfile = { workspace = true }
