[package]
name = "object_store"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clru = "0.6.1"
common_util = { workspace = true }
crc = "3.0.0"
futures = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
oss-rust-sdk = "0.6.1"
prometheus = { workspace = true }
prometheus-static-metric = { workspace = true }
prost = { workspace = true }
proto = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true }
upstream = { package = "object_store", version = "0.5.1" }

[dev-dependencies]
tempfile = { workspace = true }
