[package]
name = "object_store"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

[package.edition]
workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = "1.0"
futures = { workspace = true }
upstream = { package = "object_store", version = "0.1.0" }
oss-rust-sdk = "0.4.0"
serde = { workspace = true }
serde_derive = { workspace = true }
snafu = { workspace = true }
lru = "0.7.6"
chrono = "0.4.19"

[dev-dependencies]
tempfile = "3.1.0"
tokio = { workspace = true }
