[package]
name = "server"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
analytic_engine = { workspace = true }
arrow = { workspace = true }
async-trait = { workspace = true }
avro-rs = "0.13"
catalog = { workspace = true }
ceresdbproto = { workspace = true }
cluster = { workspace = true }
common_types = { workspace = true }
common_util = { workspace = true }
datafusion = { workspace = true }
df_operator = { workspace = true }
futures = { workspace = true }
http = "0.2"
interpreters = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
logger = { workspace = true }
meta_client = { workspace = true }
opensrv-mysql = "0.1.0"
paste = { workspace = true }
profile = { workspace = true }
protobuf = { workspace = true }
query_engine = { workspace = true }
prometheus = { workspace = true }
prometheus-static-metric = "0.5"
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
sql = { workspace = true }
system_catalog = { workspace = true }
table_engine = { workspace = true }
tokio = { workspace = true }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { workspace = true }
twox-hash = "1.6"
warp = "0.3"
bytes = { workspace = true }

[dev-dependencies]
sql = { workspace = true , features=["test"] }
