[package]
name = "bytes"
version = "0.1.0"

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
upstream = { version = "1.0", package = "bytes" }
snafu = { version ="0.6.10", features = ["backtraces"]}
