[package]
name = "ceresdb-test"
version = "0.1.0"

[package.edition]
workspace = true

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1"
ceresdb-client-rs = { git = "https://github.com/CeresDB/ceresdb-client-rs.git", rev = "a9d9190f4f7b55171ea2ad142fb41dc9909c19c5" }
sqlness = "0.2"
tokio = { workspace = true }
