[package]
name = "ceresdb-test"
version = "0.1.0"

[package.edition]
workspace = true

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1"
ceresdb-client = "1.0"
sql = { workspace = true }
sqlness = "0.4.0"
sqlparser = { workspace = true }
tokio = { workspace = true }
