[package]
name = "common_types"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["arrow_deps"]
test = []

[dependencies]
# In alphabetical order
arrow_deps = { path = "../arrow_deps", optional = true }
byteorder = "1.2"
bytes = { path = "../components/bytes" }
chrono = "0.4"
murmur3 = "0.4.1"
paste = "1.0"
proto = { path = "../proto" }
snafu = { version ="0.6.10", features = ["backtraces"]}
# TODO(yingwen): Make sqlparser support a feature
sqlparser = { version = "0.19.0", features = ["serde"]}
serde = "1.0.81"
serde_derive = "1.0.81"
serde_json = "1.0.60"
