[package]
name = "wal"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true
[features]
test = ["tempfile", "futures", "uuid"]

[dependencies.rocksdb]
git = "https://github.com/tikv/rust-rocksdb.git"
rev = "a9fbe325939c166ffc5f80e63066f5d8594a1fff"
features = ["portable"]

[dependencies]
async-trait = { workspace = true }
ceresdbproto = { workspace = true }
chrono = { workspace = true }
common_types = { workspace = true }
common_util = { workspace = true }
futures = { workspace = true, features = ["async-await"], optional = true }
log = { workspace = true }
message_queue = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true }
snafu = { workspace = true }
table_kv = { workspace = true }
tempfile = { workspace = true, optional = true }
tokio = { workspace = true }
uuid = { version = "1.3", features = ["v4"], optional = true }

[dev-dependencies]
env_logger = { workspace = true }
futures = { workspace = true, features = ["async-await"] }
rand = "0.8.5"
