[package]
name = "partitioned_lock"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
tokio = { workspace = true }

[dev-dependencies]
common_types = { workspace = true }
