[package]
name = "arrow_ext"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
arrow = { workspace = true }
snafu = { workspace = true }
zstd = { workspace = true }
