[package]
name = "catalog_impls"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies, in alphabetical order
async-trait = "0.1.53"
catalog = { path = "../catalog" }
cluster = { path = "../cluster" }
common_types = { path = "../common_types" }
common_util = { path = "../common_util" }
log = "0.4"
meta_client = { path = "../meta_client" }
snafu = { version ="0.6.10", features = ["backtraces"]}
system_catalog = { path = "../system_catalog" }
table_engine = { path = "../table_engine" }
tokio = { version = "1.0", features = ["sync"] }

[dev-dependencies]
analytic_engine = { path = "../analytic_engine", features = ["test"] }
server = { path = "../server" }
