[package]
name = "time_ext"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
# In alphabetical order
ceresdbproto = { workspace = true }
chrono = { workspace = true }
common_types = { workspace = true }
macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
