[package]
name = "bytes_ext"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
bytes = { workspace = true }
snafu = { workspace = true }
