[package]
name = "meta_client"
version = "0.1.0"

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
catalog = { workspace = true }
ceresdbproto = { workspace = true }
common_types = { workspace = true }
common_util = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
protobuf = { workspace = true }
rand = "0.7"
reqwest = "0.11"
serde = { workspace = true }
serde_derive = "1.0.81"
serde_json = "1.0.60"
snafu = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
url = "2.2"
