[package]
name = "size_ext"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
serde = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
