[package]
name = "tracing_util"
version.workspace = true
edition.workspace = true
authors = ["Databend Authors <opensource@datafuselabs.com>", "CeresDB Authors <ceresdbservice@gmail.com>"]
license = "Apache-2.0"
publish = false

[dependencies] # In alphabetical order
lazy_static = { workspace = true }
tracing = "0.1.26"
tracing-appender = "0.1.2"
tracing-subscriber = "0.2.20"
