[package]
name = "tracing_util"
authors = ["Databend Authors <opensource@datafuselabs.com>", "CeresDB Authors <ceresdbservice@gmail.com>"]
license = "Apache-2.0"
publish = false

[package.version]
workspace = true

[package.edition]
workspace = true

[dependencies]
lazy_static = { workspace = true }
serde = { workspace = true }
tracing = "0.1.26"
tracing-appender = "0.1.2"
tracing-subscriber = "0.2.20"
