[package]
name = "tracing"
version = "0.1.0"

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
upstream = { version = "0.1.26", package = "tracing" }
