[package]
name = "table_kv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common_util = { path = "../../common_util" }
log = "0.4"
obkv-table-client-rs = { git = "https://github.com/oceanbase/obkv-table-client-rs.git", rev = "318907f35de51404c05180c65440c9516fd1e10f" }
serde = "1.0"
serde_derive = "1.0"
snafu = { version = "0.6.10", features = ["backtraces"] }

[dev-dependencies]
rand = "0.7"
