[package]
name = "table_kv"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
common_util = { workspace = true }
log = { workspace = true }
obkv-table-client-rs = { git = "https://github.com/oceanbase/obkv-table-client-rs.git", rev = "5f3240ed82309640056333d980ca7a177006966e" }
serde = { workspace = true }

snafu = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
