[package]
name = "table_kv"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common_util = { workspace = true }
log = { workspace = true }
obkv-table-client-rs = { git = "https://github.com/oceanbase/obkv-table-client-rs.git", rev = "211e5718630577a7f8c1a2d74055bad4d31dea57" }
serde = { workspace = true }
serde_derive = { workspace = true }
snafu = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
