[package]
name = "skiplist"
version = "0.1.0"
authors = ["Jay Lee <busyjaylee@gmail.com>"]

[package.edition]
workspace = true

[dependencies]
rand = { workspace = true }
bytes = { workspace = true }
arena = { workspace = true }

[dev-dependencies]
yatp = { git = "https://github.com/tikv/yatp.git", rev = "4b71f8abd86890f0d1e95778c2b6bf5a9ee4c502" }
criterion = { workspace = true }

# [target.'cfg(not(target_env = "msvc"))'.dev-dependencies]
# tikv-jemallocator = "0.4.0"

[[bench]]
name = "bench"
harness = false
