[server]
bind_addr = "0.0.0.0"
http_port = 5440
grpc_port = 8831
log_level = "info"

[runtime]
read_thread_num = 4
write_thread_num = 4
background_thread_num = 4

[analytic]
write_group_worker_num = 4
replay_batch_size = 500
max_replay_tables_per_batch = 1024
write_group_command_channel_cap = 1024

[analytic.wal_storage]
type = "RocksDB"
data_dir = "/tmp/ceresdb1"

[analytic.storage]
mem_cache_capacity = '1G'
mem_cache_partition_bits = 0

[analytic.storage.object_store]
type = "Local"
data_dir = "/tmp/ceresdb"

[analytic.compaction_config]
schedule_channel_len = 4
schedule_interval = "30m"
max_ongoing_tasks = 4

[cluster_deployment]
type = "NoMeta"

# Route&Shard: public
[[cluster_deployment.topology.schema_shards]]
schema = 'public'
[[cluster_deployment.topology.schema_shards.shard_views]]
shard_id = 0
[cluster_deployment.topology.schema_shards.shard_views.endpoint]
addr = '127.0.0.1'
port = 8831

# Route&Shard: test
[[cluster_deployment.topology.schema_shards]]
schema = 'test'
[[cluster_deployment.topology.schema_shards.shard_views]]
shard_id = 0
[cluster_deployment.topology.schema_shards.shard_views.endpoint]
addr = '127.0.0.1'
port = 8831
[[cluster_deployment.topology.schema_shards.shard_views]]
shard_id = 1
[cluster_deployment.topology.schema_shards.shard_views.endpoint]
addr = '127.0.0.2'
port = 8831

# Route rules: test
[[cluster_deployment.rules.prefix_rules]]
schema = 'test'
prefix = 'BIZ'
shard = 0

[[cluster_deployment.rules.hash_rules]]
schema = 'test'
shards = [ 1 ]

[limiter]
write_block_list = ['mytable1']
read_block_list = ['mytable1']

