[server]
bind_addr = "0.0.0.0"
http_port = 5440
grpc_port = 8831

[logger]
level = "info"

[tracing]
dir = "/tmp/ceresdb"

[analytic.storage.object_store]
type = "Local"
data_dir = "/tmp/ceresdb"

[analytic.wal]
type = "RocksDB"
data_dir = "/tmp/ceresdb"

[cluster_deployment]
mode = "NoMeta"

[[cluster_deployment.topology.schema_shards]]
schema = 'public'
auto_create_tables = true

[[cluster_deployment.topology.schema_shards.shard_views]]
shard_id = 0

[cluster_deployment.topology.schema_shards.shard_views.endpoint]
addr = "127.0.0.1"
port = 8831