[server]
bind_addr = "0.0.0.0"
http_port = 5440
grpc_port = 8831
log_level = "info"

[analytic.storage]
mem_cache_capacity = '1G'
mem_cache_partition_bits = 0

[analytic.storage.object_store]
type = "Local"
data_dir = "/tmp/ceresdb"

[analytic.wal_storage]
type = "RocksDB"
data_dir = "/tmp/ceresdb"
