[package]
name = "future_ext"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[dependencies]
futures = { workspace = true }
runtime = { workspace = true }
tokio = { workspace = true, features = ["time"] }
