[package]
name = "benchmarks"
version = "0.1.0"

[package.edition]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arena = { path = "../components/arena" }
arrow2 = { version = "0.12.0", features = [ "io_parquet" ] }
arrow_deps = { path = "../arrow_deps" }
analytic_engine = { path = "../analytic_engine" }
base64 = { workspace = true }
clap = "2.0"
common_types = { workspace = true }
common_util = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
object_store = { path = "../components/object_store" }
parquet = { path = "../components/parquet"}
rand = "0.7"
serde = { workspace = true }
serde_derive = { workspace = true }
snafu = { workspace = true }
table_engine = { workspace = true }
table_kv = { path = "../components/table_kv" }
tokio = { workspace = true }
wal = {path = "../wal"}

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false

[[bin]]
name = "sst-tools"
