name: Check ASF check

on:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  style-check:
    name: style-check
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Check License Header
        uses: korandoru/hawkeye@v4
