# Copyright 2022 CeresDB Project Authors. Licensed under Apache-2.0.

name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'etc/**'
      - '.github/**'
      - '**.md'
      - '**.yml'
      - '.dockerignore'
      - 'docker/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'etc/**'
      - '.github/**'
      - '**.md'
      - '**.yml'
      - '.dockerignore'
      - 'docker/**'

# Common environment variables
env:
  RUSTFLAGS: "-C debuginfo=1"
  CARGO_TERM_COLOR: always

jobs:
  linux-ci:
    name: linux-ci
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        rust: [nightly-2022-08-08]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install ${{ matrix.rust }} --profile minimal
      - name: Cache Rust Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ./target
          key: rust-${{ runner.os }}-ci-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            rust-${{ runner.os }}-ci-${{ hashFiles('rust-toolchain') }}-
            rust-${{ runner.os }}-ci-
            rust-${{ runner.os }}
      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install --yes gcc g++ libssl-dev pkg-config cmake protobuf-compiler
          sudo rm -rf /var/lib/apt/lists/*
      - name: Install clippy rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt
      - name: Run Style Check
        run: |
          make check-license
          make clippy
          make fmt
      - name: Run Unit Tests
        run: |
          cp ${LOCK_FILE} ${LOCK_FILE}.bak
          make test-ut
          echo "Checking if ${LOCK_FILE} has changed..."
          diff ${LOCK_FILE} ${LOCK_FILE}.bak
        env:
          RUST_BACKTRACE: "1"
          LOCK_FILE: Cargo.lock
      - name: Run Harness
        run: |
          cd tests
          make run
        env:
          RUST_BACKTRACE: "1"
