name: Build Docker Image and Push to Docker Hub on Tags

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    if: github.repository_owner == 'CeresDB'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push CeresDB Server Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ceresdb/ceresdb-server:${{github.ref_name}}
